### ISSUE TITLE
Doesn't work in VIM

### ISSUE THREAD

**Issue by jackcasey** [kelp404/quick-jump#1]
Thanks for building this.

Just a heads up that this plugin doesn't currently work with VIM Mode. It works fine if you are in insert mode within VIM Mode, but if you are in command/normal mode it throws a console error and gets the editor into a broken state.

**Comment by kelp404** [comment]
Hello @jackcasey 
Please checkout the new version.

**Comment by jackcasey** [comment]
Hi @kelp404, Thanks for the new version. It does seem to mostly work. But I still manage to break it just from doing a series of moves and cancels in normal mode in VIM. I'm not sure on exact repro steps though.

Another way that seems to break it is using visual mode in vim. (Not sure if you use vim much but you might hit 'v' to start visual(selection) mode and then want to quick jump to a character later in the line etc.)

When it does break I get `Cannot call method 'invert' of null` in the console and have to restart Atom to get it behaving again.

Thanks again for looking in to it. If you decide to just not support vim mode due to all the complexities I'd understand :wink:.

**Comment by kelp404** [comment]
Hello @jackcasey 
Maybe I should research the vim-mode package.
I can find out current mode is command or insert mode. The element `.vim-mode` has class `.command-mode`, `.insert-mode`.
But I can't find out visual-mode.
