### ISSUE TITLE
cmd vs ctrl

### ISSUE THREAD

**Issue by MasseGuillaume** [kelp404/quick-jump#2]
wont work in linux/windows

```
".editor":
  "ctrl-;": "quick-jump:toggle"
```

**Comment by kelp404** [comment]
Hello @MasseGuillaume 
I think this is not my issue.
`.editor` can't bind `ctrl-;` as custom command.

Please try this:

``` coffee
'.platform-darwin .editor:not(.mini)':
    'ctrl-;': 'quick-jump:toggle'
```

**Comment by MasseGuillaume** [comment]
cuttenly you are using `cmd` and it does not work on linux

I'm suggesting that you add:

```
".editor":
  "ctrl-;": "quick-jump:toggle"
```

**Comment by kelp404** [comment]
I use OS X and it is work.

**Comment by MasseGuillaume** [comment]
yep but if you want to support multiple platforms you need to have two selectors. Example from atom core plugin [symbols view](https://github.com/atom/symbols-view/blob/master/keymaps/symbols-view.cson)

```
'.platform-darwin .editor':
  'cmd-r': 'symbols-view:toggle-file-symbols'

'.platform-win32 .editor':
  'ctrl-r': 'symbols-view:toggle-file-symbols'

'.platform-linux .editor':
  'ctrl-r': 'symbols-view:toggle-file-symbols'
```

**Comment by kelp404** [comment]
I can't check is it work on other OS, so I will not support that.
Please custom keymaps by yourself.

**Comment by kelp404** [comment]
Hello @MasseGuillaume 
I published the new version.
